### ISSUE TITLE
Update DMME's branding to "Virginia Energy"

### ISSUE THREAD

**Issue by arthursmalliii** [coopercenter/sol-tax-webapp#169]
DMME is changing its name to Virginia Energy, effective Oct. 1, 2021. They also have a new logo.

**The task:** Across the dashboard, find all mentions and appearances of the old name and logo, and replace with the new name and logo.

Details below. For the logo, screen grab from this image or (better) search online for a suitable logo image file.

The change-over doesn't need to happen on Oct. 1 exactly. Any time soon-ish is fine.

![image](https://user-images.githubusercontent.com/2918094/134822184-d40496ab-cd5c-4a68-bb31-0118270308e1.png)

**Comment by arthursmalliii** [comment]
Here's a file with the new Virginia Energy logo.

![VAEnergyLogo](https://user-images.githubusercontent.com/2918094/135475655-19bf7a6b-c869-4b75-b4e7-a26fed81722f.png)

**Comment by tcallen45** [comment]
The logo is updated on the site and all references to DMME are now to Virginia Energy. During my meeting with Elizabeth and Aaron on Wednesday, I asked Aaron if they had a logo without the white background and he said he'd get back to me if he ends up getting one.

**Comment by arthursmalliii** [comment]
The above logo file is probably fine, but just in case, here's [a link to many alternate versions](https://myuva-my.sharepoint.com/:f:/g/personal/aas9z_virginia_edu/EqH2xC10uNZJmxRi8rH_BRwB8wA8yCwBKaxATIOYCHazdA?e=T95vC2)

**Comment by arthursmalliii** [comment]
(Note: When an issue is resolved, you may click the icon to close the issue.)

**Comment by arthursmalliii** [comment]
On nomenclature:

Virginia Department of Mines Minerals and Energy is now _Virginia Department of Energy_

DMME is now _Virginia Energy_

**Comment by tcallen45** [comment]
Found an image without the background and updated it
